version: '3.4'
services:
  app:
    image: is-nebraska-great-again:latest
    restart: unless-stopped
    ports:
      - "3001:3001"
    networks:
      - traefik_public
    labels:
      - "traefik.http.routers.inga.rule=Host(`www.isnebraskagreatagain.com`) || Host(`isnebraskagreatagain.com`)"
      - "traefik.docker.network=traefik_public"
      - "traefik.http.services.inga.loadbalancer.server.port=3001"

networks:
  traefik_public:
    external: true